sudo: false
language: php
php:
- 5.4
- 5.5
- 5.6
env:
- WP_VERSION=latest
- WP_VERSION=4.0
- WP_VERSION=3.9
matrix:
  include:
  - php: hhvm
    env: WP_VERSION=latest
  allow_failures:
  - php: hhvm
before_script:
- composer install
- bash tests/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
notifications:
  slack:
    secure: tlfmIXDTcUZOsq5ZE+N+rWZy4tChnqy87qQ7gtNKB1Dxe0q9xqWH9J+BmeVrT/fmZ+gsHIgxckvyeSnGdbnNx35EB8xJu4Pim1yXL7yj1YWIL1jmxeUIMKtPdQqDxw7tAu36Bk2o+pyH43OtJoKGWg+v9vVIL81Rz9Otlmux1x4=
